"""empty message

Revision ID: 715fc02cea3
Revises: None
Create Date: 2014-08-19 17:30:54.534449

"""

# revision identifiers, used by Alembic.
revision = '715fc02cea3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cargo_name', sa.String(255), nullable=True),
        sa.Column('cargo_weight', sa.Float(), nullable=False),
        sa.Column('cargo_status', sa.String(255), nullable=False),
        sa.Column('cargo_detail', sa.Text(), nullable=True),

        sa.Column('date_from', sa.DateTime(), nullable=False),
        sa.Column('date_to', sa.DateTime(), nullable=False),
        sa.Column('require_truck_info', sa.String(255), nullable=True),
        sa.Column('city_from', sa.String(255), nullable=False),
        sa.Column('city_to', sa.String(255), nullable=False),
        sa.Column('pay_type', sa.String(255), nullable=True),

        sa.Column('contacts', sa.String(255), nullable=False),
        sa.Column('phone_num', sa.String(100), nullable=False),
        sa.Column('publish_org', sa.String(255), nullable=True),
        sa.Column('address', sa.Text(), nullable=False),

        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    ### end Alembic commands ###
